updateBranch: true
deleteBranchAfterMerge: false
reportStatus: true

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
- minApprovals:
    OWNER: 1
- requiredLabels:
  - merge

mergeCommitMessage: "{title} (#{number})"
